sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t m971119/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true m971119/docker-react-udemy npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-react-udemy'
  env: 'Dockerreactudemy-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-991759158532'
  bucket_path: 'docker-react-udemy'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
