sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t m971119/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true m971119/docker-react-udemy npm run test